### PR TITLE
suggested replacement of setting variable NOCAPTCHA

### PR DESCRIPTION
**Pull request by acpmasquerade**
Instead of NOCAPTCHA, setting variable used at RECAPTCHA_NOCAPTCHA

### CODE REVIEW

**Comment by hedleyroos** [comment]
I can't add this because there are existing deploys using the NOCAPTCHA variable. I will be adding a RECAPTCHA = {} setting soon because a dictionary is extensible and doesn't pollute the settings namespace.

**Comment by acpmasquerade** [comment]
RECAPTCHA ={} will be much appreciated.

**Comment by hedleyroos** [comment]
Wow, it's been a year since I promised this. :( Will make a point release and then fit this issue in before 26 Jan 2016.

**Comment by Phrohdoh** [comment]
Hey @hedleyroos, any updates on this?

**Comment by AltusBarry** [comment]
We no longer support the NOCAPTCHA option.

**Pull request closed without merging**
