### PR TITLE
Test with Django 1.8, 1.9, 1.10, and Python 3.5

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by gustavi** [comment]
Thank you for this PR. Someone can review and merge it ?

**Comment by adamchainz** [comment]
+1 would like more modern compat

**Comment by gustavi** [comment]
up !

**Comment by adamchainz** [comment]
I'm now a maintainer 😄 

Merged in 2f8b89c2d8090dd53d027759991af18d266cb4be, thanks @scop !

**Pull request closed without merging**
